parameters:
  terraformCommand: ''
  subscription: ''
  source: ''
  workload: ''
  environment: ''
  region: ''

jobs:
- job: terraform_${{ parameters.terraformCommand }}
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: pscore
      scriptLocation: inlineScript
      addSpnToEnvironment: True
      inlineScript: |
        cd terraform/${{ parameters.source }}
        
        $env:ARM_CLIENT_ID = $env:servicePrincipalId
        $env:ARM_CLIENT_SECRET = $env:servicePrincipalKey 
        $env:ARM_TENANT_ID = $env:tenantId 
        $env:ARM_SUBSCRIPTION_ID = az account show --query 'id' --output tsv

        $env:TF_VAR_workload="${{ parameters.workload }}"
        $env:TF_VAR_environment="${{ parameters.environment }}"
        $env:TF_VAR_region="${{ parameters.region }}"
        
        terraform init
        Write-Output ${{ parameters.terraformCommand }}
        if ('${{ parameters.terraformCommand }}' -eq 'apply' -or '${{ parameters.terraformCommand }}' -eq 'destroy') {
            terraform ${{ parameters.terraformCommand }} --auto-approve
        } else {
        terraform ${{ parameters.terraformCommand }}
        }
