trigger:
  - none

parameters:
- name: subscription
  type: string
  default: 'SPN-accesaplayground'
- name: storageAccRg
  type: string
  default: 'rg-common-resources'
- name: storageAccName
  type: string
  default: 'tfstateaccesafunctions'
- name: storageAccLocation
  type: string
  default: 'westeurope'
- name: storageContainerName
  type: string
  default: 'my-eventcontainer'
- name: stages
  type: object
  default: 
  - validate
  - plan
  - apply
- name: workload
  type: string
  default: 'tagging'
- name: environment
  type: string
  default: 'test'
- name: region
  type: string
  default: 'westeurope'

stages:

- stage: storageEvent
  jobs:
  - job: check_storage
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{ parameters.subscription }}
        scriptType: pscore
        scriptLocation: 'scriptPath'
        addSpnToEnvironment: True
        arguments: '${{ parameters.storageAccRg }} ${{ parameters.storageAccName }} ${{ parameters.storageAccLocation }} ${{ parameters.storageContainerName }}'
        scriptPath: 'pipelines/scripts/storage-check.ps1'

- ${{ each value in parameters.stages }}:
  - template: templates/terraform-stage-template.yml
    parameters:
      name: ${{ value }}
      subscription: ${{ parameters.subscription }}
      source: 'tag-function'
      workload: ${{ parameters.workload }}
      environment: ${{ parameters.environment }}
      region: ${{ parameters.region }}
